### PR TITLE
Issue #184 Log TraceId

### PR DESCRIPTION
**Pull request by gregw**
Issue #184 Log TraceId

_This is not yet ready for merge as it is insufficiently tested.  Creating PR for review of the approach._

Changed the LogContext to be a permanent concurrent HashMap on all threads.
Moved generation of traceId to VmApiProxyEnvironment
Add the traceId to the LogContext in VmRuntimeWebAppContext.ContextListener

### CODE REVIEW

**Comment by gregw** [comment]
I believe this is working.  @ludoch can you confirm that traceId is doing it's thing in this [deployed version](https://console.cloud.google.com/logs?project=jetty9-work&authuser=1&key1=default&service=appengine.googleapis.com&key2=20160302t221446&logName=appengine.googleapis.com%2Fapp&minLogLevel=0&expandAll=false&timezone=Europe%2FParis&lastVisibleTimestampNanos=1456953883663000000)

**Comment by gregw** [comment]
@ludoch note that the traceid is only valid for logs generated from within a request context.   Is there meant to be a traceid for the default env?

**Comment by ludoch** [comment]
This is fine. LGTM

**Comment by ludoch** [comment]
But need a merge.

**Comment by ludoch** [comment]
To Greg for the merge.

**Pull request merged**
