### PR TITLE
Download gcloud debugger from known public location #96

### PR DESCRIPTION
**Pull request by gregw**
Following advice for work around for cloud debugger from #96

### CODE REVIEW

**Comment by vlad-lifliand** [comment]
This is going to work, but not too well:
1. It is possible that different instances of the same version will be using different versions of the debugger agent. It will happen, for instance, if the number of instances is increased after a newer version of the debugger agent was released. We would like to avoid this kind of asymmetry.
2. Every instance just downloads file from the same URL, on every boot. This is just wasteful.
3. It is also more complicated than necessary. The solution we had for java7 was snapshotting the debugger agent version on deployment, but it doesn't work for custom runtimes.

I suggest simplifying the whole thing as following:
1. Add debugger agent binary to the Docker image by adding this line to Dockerfile:
ADD https://storage.googleapis.com/cloud-debugger/appengine-java/current/cdbg_java_agent.tar.gz /home/vmagent/cdbg
(it will also unpack files automatically)
2. jetty_run.sh just need the last part of formatting the command line:
DBG_AGENT="$( /home/vmagent/cdbg/format-env-appengine-vm.sh )"

**Comment by ludoch** [comment]
Thanks Vlad!
Greg: let's do as Vlad said.

**Comment by gregw** [comment]
@ludoch Should I install the cdbg_java_agent.tar.gz in the gce-openjdk, gce-jetty or appengine-mvn-opensource image?     I think gce-openjdk can have it installed?

**Comment by gregw** [comment]
@vlad-lifliand  is /home/vmagent/cdbg a well known location?
There has been some discussion of adding other jars to the openjdk image and /usr/local/share/java or /usr/share/java may be a better place to install such libraries?

**Comment by gregw** [comment]
@ludoch I'm guessing I should do the same for the profiler?
```shell
    CPROF_AGENT_URL="https://storage.googleapis.com/cloud-profiler/appengine-java/current/cloud_profiler_java_agent.tar.gz"
```

**Comment by gregw** [comment]
I've updated the PR #105 so that it installs both the cloud debugger and cloud profiler into the gce-debian-openjdk image.    Both the jetty and gae images have been updated to use these installed versions.

Note that I don't yet know how to test that these work.

Also note circleci is failing until #108 is merged.

**Comment by vlad-lifliand** [comment]
Good. I don't have any opinion where the debugger binaries should go. Note
that it's not just a jar file...

**Pull request merged**
