### PR TITLE
Create /var/log/app_engine directory #313

### PR DESCRIPTION
**Pull request by gregw**
Create /var/log/app_engine directory #313

### CODE REVIEW

**Comment by meltsufin** [comment]
LGTM

**Comment by ludoch** [comment]
What is the side effect on Compat, (or even flex) where I think this directory path is provided as a Docker volume? Someone has to check this PR on a real image for both pure openjdk and compat...

**Comment by meltsufin** [comment]
That's a good point. The issue was raised based on a local run of the image without mounting the logs volume, but if the volume is always mounted when the App Engine run the image, it may not be an actual issue. We just need to fix the README to instruct mounting of the logs volume.

**Comment by gregw** [comment]
no longer required

**Pull request closed without merging**
