### PR TITLE
sort imports acording to the Google style

### PR DESCRIPTION
**Pull request by aozarov**

### CODE REVIEW

**Comment by ludoch** [comment]
Which tool did you use?

**Comment by gregw** [comment]
@aozarov I think it is a good idea to get all the code reformatted like this.  However once done, we need very good style configurations for eclipse and IDEA, so that reformats will produce no changes at all.

**Comment by aozarov** [comment]
@ludoch , I used the internal sort tool
```
find . -name '*.java' | xargs sort_java_imports.py 
```

@gregw, indeed. see [google-java-format](https://github.com/google/google-java-format)
This is the rule for sort order: https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing
Both eclipse and intelliJ have options to specify this order (I can share my settings with you if you want). Also, they have an option to cleanup unused import statements.

**Comment by aozarov** [comment]
Also, looks like sort order would be part of the google-java-format once this [bug](https://github.com/google/google-java-format/issues/42) is fixed.

**Comment by ludoch** [comment]
lgtm

**Pull request merged**
