### PR TITLE
updated to jetty-9.3.7.RC1

### PR DESCRIPTION
**Pull request by gregw**
Fix for quickstart issue identified in #150

### CODE REVIEW

**Comment by ludoch** [comment]
Before we merge, I would like to do a release to maven of the content of this branch. 
Then I can merge tomorrow.
Or what is the timeline for RCs to be GA?

**Comment by gregw** [comment]
We don't have a formal time between RC and final releases, and often don't do RC's for point releases.  We are waiting for one other unrelated issue, which needs to be fixed today or will be in the next release, so we can probably have a 9.3.7.v201601xx before the end of the week.

**Comment by ludoch** [comment]
I would wait, as we would not push an image based on RC code I think.

**Comment by gregw** [comment]
@ludoch updated for openssl debs, which again changed in non durable store.

**Comment by gregw** [comment]
This PR is perhaps no longer needed as #162 updates to the GA version

**Pull request merged**
