### PR TITLE
Adding a basic .travis.yml

### PR DESCRIPTION
**Pull request by aozarov**

### CODE REVIEW

**Comment by aozarov** [comment]
I signed it!

**Comment by ludoch** [comment]
Hummm.. Maybe travis does not support docker builds?

**Comment by ludoch** [comment]
ha, it does but need config: https://docs.travis-ci.com/user/docker/

**Comment by aozarov** [comment]
build pass now! Thanks @ludoch

**Comment by ludoch** [comment]
LGTM

**Pull request merged**
