### PR TITLE
Explode WAR into $JETTY_BASE/webapps/root

### PR DESCRIPTION
**Pull request by chanseokoh**
Doing the same thing in #213 on the master branch.

### CODE REVIEW

**Comment by chanseokoh** [comment]
Updated the files according to the latest discussion in #213. PTAL.

**Comment by chanseokoh** [comment]
Interesting. Some tests are failing.

**Comment by gregw** [comment]
Not sure why circleci failed to build.  The PR builds cleanly for me.   Can you push a trivial commit to your branch to trigger a rebuild?

**Comment by ludoch** [comment]
relevant lines of circleCI ?:
ppengine-java-vm-runtime/appengine-jetty-managed-runtime/target/webapps/testwebapp/,UNAVAILABLE}
2016-04-21 13:23:54.393:INFO:oejs.Server:JettyRunnerThread: jetty-9.3.5.v20151012
2016-04-21 13:23:54.455:INFO:oejsh.ContextHandler:JettyRunnerThread: Started c.g.a.v.j.VmRuntimeWebAppContext@510f9489{/,file:///home/ubuntu/appengine-java-vm-runtime/appengine-jetty-managed-runtime/target/webapps/testwebapp/,AVAILABLE}
2016-04-21 13:23:54.456:INFO:oejs.AbstractNCSARequestLog:JettyRunnerThread: Opened /home/ubuntu/appengine-java-vm-runtime/appengine-jetty-managed-runtime/target/logs/request.2016_04_21.log
2016-04-21 13:23:54.457:INFO:oejs.ServerConnector:JettyRunnerThread: Started ServerConnector@12f355d1{HTTP/1.1,[http/1.1]}{0.0.0.0:52635}
2016-04-21 13:23:54.457:INFO:oejs.Server:JettyRunnerThread: Started @15466ms
2016-04-21 13:23:54.457:INFO:oejs.Server:JettyRunnerThread: Started!
2016-04-21 13:23:54.457:INFO:oejs.Server:main: Waited!
2016-04-21 13:23:54.479:INFO:oejs.ServerConnector:main: Stopped ServerConnector@12f355d1{HTTP/1.1,[http/1.1]}{0.0.0.0:52635}
2016-04-21 13:23:54.481:INFO:oejsh.ContextHandler:main: Stopped c.g.a.v.j.VmRuntimeWebAppContext@510f9489{/,file:///home/ubuntu/appengine-java-vm-runtime/appengine-jetty-managed-runtime/target/webapps/testwebapp/,UNAVAILABLE}
2016-04-21 13:23:54.548:INFO:oejs.Server:JettyRunnerThread: jetty-9.3.5.v20151012
2016-04-21 13:23:54.587:INFO:oejsh.ContextHandler:JettyRunnerThread: Started c.g.a.v.j.VmRuntimeWebAppContext@4a570844{/,file:///home/ubuntu/appengine-java-vm-runtime/appengine-jetty-managed-runtime/target/webapps/testwebapp/,AVAILABLE}
2016-04-21 13:23:54.588:INFO:oejs.AbstractNCSARequestLog:JettyRunnerThread: Opened /home/ubuntu/appengine-java-vm-runtime/appengine-jetty-managed-runtime/target/logs/request.2016_04_21.log
2016-04-21 13:23:54.589:INFO:oejs.ServerConnector:JettyRunnerThread: Started ServerConnector@37de6f23{HTTP/1.1,[http/1.1]}{0.0.0.0:57041}
2016-04-21 13:23:54.590:INFO:oejs.Server:JettyRunnerThread: Started @15598ms
2016-04-21 13:23:54.590:INFO:oejs.Server:JettyRunnerThread: Started!
2016-04-21 13:23:54.590:INFO:oejs.Server:main: Waited!
2016-04-21 13:23:54.608:INFO:oejs.ServerConnector:main: Stopped ServerConnector@37de6f23{HTTP/1.1,[http/1.1]}{0.0.0.0:57041}
2016-04-21 13:23:54.618:INFO:oejsh.ContextHandler:main: Stopped c.g.a.v.j.VmRuntimeWebAppContext@4a570844{/,file:///home/ubuntu/appengine-java-vm-runtime/appengine-jetty-managed-runtime/target/webapps/testwebapp/,UNAVAILABLE}
Tests run: 13, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.077 sec <<< FAILURE! - in com.google.apphosting.vmruntime.jetty9.VmRuntimeJettyKitchenSinkTest
testHealthOK(com.google.apphosting.vmruntime.jetty9.VmRuntimeJettyKitchenSinkTest)  Time elapsed: 0.022 sec  <<< ERROR!
java.lang.IllegalStateException: server state=STOPPED
	at com.google.apphosting.vmruntime.jetty9.JettyRunner.waitForStarted(JettyRunner.java:77)
	at com.google.apphosting.vmruntime.jetty9.VmRuntimeTestBase.setUp(VmRuntimeTestBase.java:185)
	at com.google.apphosting.vmruntime.jetty9.VmRuntimeJettyKitchenSinkTest.setUp(VmRuntimeJettyKitchenSinkTest.java:50)

Running com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContextTest
2016-04-21 13:23:54.720:INFO:oejs.Server:JettyRunnerThread: jetty-9.3.5.v20151012
2016-04-21 13:23:54.792:INFO:oejsh.ContextHandler:JettyRunnerThread: Started c.g.a.v.j.VmRuntimeWebAppContext@1642d120{/,file:///home/ubuntu/appengine-java-vm-runtime/appengine-jetty-managed-runtime/target/webapps/testwebapp/,AVAILABLE}

**Comment by chanseokoh** [comment]
I pushed a commit a couple of days ago, and the test failed again. I just pushed an empty commit, but I expect it will fail again.

**Comment by chanseokoh** [comment]
Hmm... all checks have passed. Did you fix the test? Anyway, looks like we are good to go.

When will the base openjdk8 image available for public download?

**Comment by gregw** [comment]
@chanseokoh I did not change the test.  When it failed in CI, the ISE indicates the server is just not started, which suggests a fragile unit test more than a problem with the software.  Either way, I cannot see how the failure is related to this change.  But just in case, I'll run some manual tests on master today before merging this.

**Comment by ludoch** [comment]
Merging.

**Pull request merged**
